### ISSUE TITLE
Adding configurable namespace for redis keys

### ISSUE THREAD

**Issue by ghost** [davechallis/ocypod#22]
All of the keys are specific in the keys file:
https://github.com/davechallis/ocypod/blob/master/src/application/keys.rs

The issue is that for redis servers which are used by multiple applications, the designated key names could possibly clash with a keys used by other applications with something as generic as `failed` etc. One solution is to allow this value to be configurable and used in the keys.rs to build the key name. e.g. default `ocypod:failed` versus `failed`. This also makes it easier to scan for keys only belonging to the ocypod application.

**Comment by davechallis** [comment]
Sounds like a good idea to me. I'll probably add a configuration option to set the namespace, but leave it as blank (i.e. no namespace, same as now) if not specified, just to avoid breaking backwards compatibility with existing setups if people upgrade.

I'd probably change this default in future to e.g. `ocypod:failed` as you suggested next major release though, since there are some other breaking changes that I'd like to add too.
